$Rosewater = rgba(245, 224, 220, 1);
$Flamingo = rgba(242, 205, 205, 1);
$Pink = rgba(245, 194, 231, 1);
$Mauve = rgba(203, 166, 247, 1);
$Red = rgba(243, 139, 168, 1);
$Maroon = rgba(235, 160, 172, 1);
$Peach = rgba(250, 179, 135, 1);
$Yellow = rgba(249, 226, 175, 1);
$Green = rgba(166, 227, 161, 1);
$Teal = rgba(148, 226, 213, 1);
$Sky = rgba(137, 220, 235, 1);
$Sapphire = rgba(116, 199, 236, 1);
$Blue = rgba(137, 180, 250, 1);
$Lavender = rgba(180, 190, 254, 1);
$Text = rgba(205, 214, 244, 1);
$Subtext1 = rgba(186, 194, 222, 1);
$Subtext0 = rgba(166, 173, 200, 1);
$Overlay2 = rgba(147, 153, 178, 1);
$Overlay1 = rgba(127, 132, 156, 1);
$Overlay0 = rgba(108, 112, 134, 1);
$Surface2 = rgba(88, 91, 112, 1);
$Surface1 = rgba(69, 71, 90, 1);
$Surface0 = rgba(49, 50, 68, 1);
$Base = rgba(30, 30, 46, 1);
$Mantle = rgba(24, 24, 37, 1);
$Crust = rgba(17, 17, 27, 1);

$background = $Base;
$foreground = $Text;

$card = $Surface0;
$cardForeground = $Text;

$popover = $Surface1;
$popoverForeground = $Text;

$primary = $Blue;
$primaryForeground = $Base;

$secondary = $Sapphire;
$secondaryForeground = $Base;

$muted = $Surface2;
$mutedForeground = $Subtext0;

$accent = $Mauve;
$accentForeground = $Base;

$success = $Green;
$successForeground = $Base;

$warning = $Peach;
$warningForeground = $Base;

$destructive = $Red;
$destructiveForeground = $Base;

$border                   alpha($Overlay1, 0.6);
$input = $Surface0;
$ring = $Blue;