source = $HOME/.config/hypr/theme/theme.conf

general {
    fade_in_duration = 200
    fade_out_duration = 200
    unlock_on_switch = true
    hide_cursor = true
}

background {
    monitor =
    path = $HOME/.config/hypr/wallpapers/wallhaven-d6q5dm.png  
    # color = $foreground
    # all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations
    blur_size = 2
    blur_passes = 3 # 0 disables blurring
    noise = 0.0117
    contrast = 1.3000 # Vibrant!!!
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

# Key layout
label {
    monitor =
    text = cmd[update:18000000] echo "<span>  <b>$LAYOUT</b></span>"
    color = $foreground
    font_size = 12
    font_family = JetBrainsMono Nerd Font 10
    position = -10, -10
    halign = right
    valign = top
}


# Time
label {
    monitor =
    text = cmd[update:18000000] echo "<b>"$TIME12"</b>"
    color = rgba(205, 214, 244, 1);
    font_size = 100
    font_family = JetBrainsMono Nerd Font 10
    position = 0, 250
    halign = center
    valign = center
}

# Today
label {
    monitor =
    text = cmd[update:18000000] echo "<b><big> "$(date +'%A')" </big></b>"
    color = $color7
    font_size = 22
    font_family = JetBrainsMono Nerd Font 10
    position = 0, 100
    halign = center
    valign = center
}

# Week
label {
    monitor =
    text = cmd[update:18000000] echo "<b> "$(date +'%d %b')" </b>"
    color = $color7
    font_size = 18
    font_family = JetBrainsMono Nerd Font 10
    position = 0, 70
    halign = center
    valign = center
}

# Password Input field 
input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.5) 

    outer_color = rgba(127, 132, 156, 1);
    check_color= rgba(00ff99ee) rgba(ff6633ee) 120deg

    fail_color=rgba(ff6633ee) rgba(ff0066ee) 40deg
    fail_text = <span>$FAIL <b>($ATTEMPTS)</b></span>

    fade_on_empty = true

    placeholder_text = <b>Type your password...</b> # Text rendered in the input box when it's empty.
    font_family = JetBrainsMono Nerd Font 10
    font_size = 16

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    position = 0, -20
    halign = center
    valign = center
}

# Degrees
label {
    monitor =
    text = cmd[update:18000000] echo "<b>Feels like<big> $(curl -s "wttr.in/-6.79,-79.83?format=%t" | tr -d '+') </big></b>"
    color = $color7
    font_size = 18
    font_family = JetBrainsMono Nerd Font 10

    position = 0, 40
    halign = center
    valign = bottom
}

